# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89476a1f4fc479d89b843b9bb910302b7666826fe3be4bd3b196bce48e3e16a667ca300f624c5e0e6c91ff4a32c9c6746db86b34ed875f2df1ade29a581b3554

test:
  secret_key_base: 7e23dc7ed46858cc838d3a8627dee29241c52c336bc241d87b81d42acae4eaad9589aa8bc9e6dd02ffa8e24bdc960d791839892a10699f41a8e77c0502cdcf28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
